---
name: vars-finder

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths: ["vars"]
    tags:
      - '*'

env:
  IMAGE_NAME: ${{ github.event.repository.name }}
  BUILD_ARGS: |
          ARG BUILD_ARCH
          ARG BUILD_DATE
          ARG BUILD_DESCRIPTION
          ARG BUILD_NAME
          ARG BUILD_REF
          ARG BUILD_REPOSITORY
          ARG BUILD_VERSION
          ARG BUILD_FROM

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Extract Label from JSON
        id: get_json_label
        run: |
            # Uses yq (pre-installed on GitHub runners) to parse the yaml file
            LABEL=$(yq -r '.version' config.yaml)
            echo "label=$LABEL" >> "$GITHUB_OUTPUT"

      - name: Use Extracted Label
        run: |
          echo "The extracted label is ${{ steps.get_json_label.outputs.label }}"

      #- name: Extract variable
       # run: |
       #   CONTENT=$(curl -s https://raw.githubusercontent.com/habuild/hassio/main/haos-sbfspot/config.yaml)
       #   conf_version=$(echo "$CONTENT" | jq -r '.version')
       #   echo "CONFIG_VERSION=$conf_version" >> $GITHUB_ENV
      
      - name: Display Vars via GITHUB_ENV.CONFIG_VERSION
        run: echo The var GITHUB_ENV.CONFIG_VERSION is "$GITHUB_ENV.CONFIG_VERSION" switches between Main and version
    
      - name: Display Vars via GITHUB_REF_NAME
        run: echo The var GITHUB_REF_NAME is "$GITHUB_REF_NAME" switches between Main and version

      - name: Display Vars via Github Context github.event.release.tag_name only shows on release usage
        run: echo The Var is "${{ github.event.release.tag_name }}"

      - name: Display Vars via github.event.repository.name
        run: echo The var is "${{ github.event.repository.name }} "

      - name: Display Vars via  BUILD_ARCH
        run: echo The var BUILD_ARCH is "${BUILD_ARCH} "

      - name: Display Vars via  BUILD_DATE
        run: echo The var BUILD_DATE is "${BUILD_DATE} "

      - name: Display Vars via  BUILD_REPOSITORY
        run: echo The var BUILD_REPOSITORY is "${BUILD_REPOSITORY} "

      - name: Display Vars via BUILD_REF
        run: echo The var BUILD_REF is "${BUILD_REF} "

      - name: Display Vars via BUILD_VERSION
        run: echo The var BUILD_VERSION is "${BUILD_VERSION} "

      - name: Display Vars via BUILD_FROM
        run: echo The var BUILD_FROM is "${BUILD_FROM}"

      - name: Display Vars via  env.IMAGE_NAME /Dockerfile
        run: echo "The var is ./.${{ env.IMAGE_NAME }}/Dockerfile "
